blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ General Questions
    url: https://github.com/TechRecruiterMX/stock-metrics-challenge/discussions
    about: Ask questions or share feedback in the Discussions tab.

